### ISSUE TITLE
Addressing CI issues

### ISSUE THREAD

**Issue by Adoni5** [LooseLab/readfish#262]
Encountered a couple of issues in the CI pipeline after release.

```[tasklist]
### Tasks
- [ ] https://github.com/LooseLab/readfish/issues/263
- [ ] https://github.com/LooseLab/readfish/issues/264
- [ ] https://github.com/LooseLab/readfish/issues/265
```

**Comment by Adoni5** [comment]
Completed!
