### ISSUE TITLE
ReadMe Docs need to be updated with current images and performance metrics.

### ISSUE THREAD

**Issue by mattloose** [LooseLab/readfish#268]
ReadMe is out of date with respect to current minknow version. Images need updating and stats should be updated.
```[tasklist]
### Tasks
- [x] Update images
- [x] Provide 5khz bulk file (MinION and Prom?
- [x] run and report example stats.
- [x] switch mentions of guppy to dorado
```

**Comment by mattloose** [comment]
5khz gridION bulkfile is now available. Will generate approriate data for PromethION soon.
