### ISSUE TITLE
CI QOL improvements

### ISSUE THREAD

**Issue by Adoni5** [LooseLab/readfish#280]
Some QOL of life improvements to the CI for rEaDFiSh. A number of small changes that will improve how we report results, add sensible time outs, and split the jobs into more logical Build/Deploy stages.

```[tasklist]
### Tasks
- [x] Timeout on Jobs, suggesting 5 minutes
- [x] Pip dependency caching - it's good practice
- [x] Add extra arguments for `pytest` to `pyproject.toml` to simplfy pytest comands
- [x] Split building docs and deploying docs.
- [x] Docs should deploy on a release tag, otherwise not.
- [x] Test Summary markdown in report.
- [x] Code coverage steps
- [x] Exclude developers from FaqTory harassment
```
