### ISSUE TITLE
Resolve barcode region issue.

### ISSUE THREAD

**Issue by mattloose** [LooseLab/readfish#297]
As identified in #289 we inadvertently created a requirement for a region on the statistics class. A partial workaround is suggested in the associated branch but this is just a temporary workaround in that statistics still expects a region where it should use a barcode instead.

```[tasklist]
### Tasks
- [x] Remove absolute requirement for a region in statistics and instead use barcode where barcode is in use.
- [x] confirm barcode tomls do not require a region
- [x] double check example tomls for region/barcode conflicts.
```

**Comment by mattloose** [comment]
Closed in #299
