### ISSUE TITLE
Detect MinKNOW version and warn.

### ISSUE THREAD

**Issue by mattloose** [LooseLab/readfish#349]
As of MinKNOW 5.9 there is a change in how unblocks will be handled. To address this we should implement:

```[tasklist]
### Tasks
- [x] Detect MinKNOW version on launch and check compatibility
- [x] Proceed as usual if readfish and minknow are compatible.
- [x] If not compatible, alert user and recommend alternate versions of readfish.
```

**Comment by Adoni5** [comment]
Closed in #351, and has been released in https://github.com/LooseLab/readfish/releases/tag/2024.2.0
